name: Snowflake Test
on:
  push:
    branches:
       -main

jobs:
  test:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4

       - uses: snowflakedb/snowflake-actions@v3

       - name:Check Snowflake CLI
         run: snow  --version        

  

