name: Snowflake Test
on:
  push:
    branches:
      - main

jobs:
  test:
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4

      - uses: snowflakedb/snowflake-actions@v3
        
      - name: Create Snowflake Config
        run: |
          mkdir -p ~/.snowflake
          cat > ~/.snowflake/config.toml << EOF
          default_connection_name = "default"

          [connections.default]
          account = "${SNOWFLAKE_ACCOUNT}"
          user = "${SNOWFLAKE_USER}"
          password = "${SNOWFLAKE_PASSWORD}"
          warehouse = "COMPUTE_WH"
          database = "USERSRNARAVA"
          schema = "PUBLIC"
          role = "ACCOUNTADMIN"
          EOF
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Test Connection
        run: snow connection test

  

